# Generated by Django 5.0.1 on 2024-01-08 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('member', 'member'), ('moderator', 'moderator')], default='member', max_length=10, null=True, verbose_name='Роль'),
        ),
    ]
